### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by LuciaAnsino** [puchy22/nutri-app#6]
Hay que elegir un lenguaje de programación para hacer tu proyecto, es recomendable que se puedan definir estructuras de datos y variables privadas.

**Comment by puchy22** [comment]
Hola, había pensado que la mejor opción sería usar Deno con TypeScript ya que cumple los requisitos que has mencionado además de ser una opción fuertemente tipada y con buen rendimiento. Además que JavaScript me parece un lenguaje interesante de aprender ya que a día de hoy se usa para casi todo.
